/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.Random;
import java.util.List;
import java.util.ArrayList;
import java.util.Hashtable;
import java.util.stream.IntStream;

import org.chocosolver.solver.*;
import org.chocosolver.solver.constraints.Constraint;
import org.chocosolver.solver.search.strategy.Search;
import org.chocosolver.solver.variables.IntVar;
import org.chocosolver.util.tools.ArrayUtils;


public class App {
    static Model m = new Model();


    static IntVar[] navCSP(IntVar[] source, IntVar[][] sources, int lb, int ub, IntVar dummy){
        int s = source.length;
        int ss = sources[0].length;
        int sss = s*ss;
        IntVar[] out = m.intVarArray(sss,lb,ub);
        IntVar[] dummies = new IntVar[ss]; for(int i=0;i<ss;i++) dummies[i] = dummy;//copy dummy ss times
        // IntVar[] table = ArrayUtils.concat(ArrayUtils.flatten(sources),dummies); //flatten sources, dummies at the end (ub--)
        IntVar[] table = ArrayUtils.concat(dummies, ArrayUtils.flatten(sources)); //flatten sources, dummies at the end (lb++)
        
        // for(int i=0;i<sss;i++) m.element(out[i], table, pointer,0);
        int k=0;
        for(int i=0; i<s;i++) for(int j=0;j<ss;j++){
            System.out.println("navCSP part "+i);
            IntVar pointer = source[i].mul(ss).add(j).intVar(); // = pointer arithm
            m.element(out[k++], table, pointer,0).post();
        }
        return out;
    }

    private static void shuffleArray(int[] array){
        int index;
        Random random = new Random();
        for (int i = array.length - 1; i > 0; i--)
        {
            index = random.nextInt(i + 1);
            if (index != i)
            {
                array[index] ^= array[i];
                array[i] ^= array[index];
                array[index] ^= array[i];
            }
        }
    }

    public static void main(String[] args) {
        // Problem Size
        int objects=20;
        int n=3; //MaxCard
        int r=3; //navigations
        int magic =10; //how many attributes are the same

        // Object we apply the constraints to (IDs start at 1)
        int startObj = 1;

        // Make Data
        int[] attribs = new int[objects];
        for(int i=0;i<objects;i++) attribs[i]= i%magic +10;
        // shuffleArray(attribs);
        IntVar[][] attribTable = new IntVar[objects][1]; //objects number of variables of domain of size 1
        for(int i=0;i<objects;i++){
            attribTable[i][0] = m.intVar("attrib",attribs[i]);
            System.out.println(attribTable[i][0].getValue());
        }


        IntVar[][] table = m.intVarMatrix("table",objects, n, 0, objects); //objectsXn variables of domain of size objects
        IntVar dummy = m.intVar(0);

        // IntVar[] vars = table[startObj];
        // for(int i=0;i<r;i++){
        //     vars = navCSP(vars, table, 0, n, dummy);
        // }
        IntVar[] vars = navCSP(table[startObj], attribTable, 0, magic+10, dummy);

        m.allDifferentExcept0(vars).post();
        // m.allDifferent(vars).post();

        IntVar sum = m.intVar("sum",0, 1000);
        m.sum(vars, "=", sum).post();
        m.setObjective(true, sum);

        m.getSolver().setSearch(Search.intVarSearch(ArrayUtils.flatten(table)), Search.inputOrderLBSearch(m.retrieveIntVars(true)));

        List<Solution> front = m.getSolver().findParetoFront(ArrayUtils.flatten(table),Model.MAXIMIZE); 
        System.out.println("The pareto front has "+front.size()+" solutions : ");
        for(Solution s: front){
                System.out.println(s);
        }



        // Solution solution = m.getSolver().findSolution();
        // if(solution != null){
        //     System.out.println(solution.toString());
        // } else {
        //     System.out.println("mmmhh");
        // }


    }
}
